// Metadata created by nebel
//
// ParentAssemblies: generated-master.adoc

[id="con_cnf_pods"]
= Pods
//In the title of concept modules, include nouns or noun phrases that are used in the body text. This helps readers and search engines find the information quickly.
//Do not start the title of concept modules with a verb. See also _Wording of headings_ in _The IBM Style Guide_.

[role="_abstract"]
Pods are the smallest deployable units of computing that can be created and managed in OpenShift.

A Pod can contain one or more running containers at a time. Applications / containers running in the same Pod have access to several of the same namespaces. For example, each application has access to the same network namespace, meaning that one running container can communicate with another running container over 127.0.0.1:<port>.

The same applies to storage volumes, since the containers are in the same Pod, they have access to the same storage namespace, and can both mount the same volume. Of course, care must be taken in this configuration to prevent any data corruption.

.Sample code block
[source,yaml]
----
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
    name: performance-addon-operator
    namespace: openshift-performance-addon-operator
spec:
    channel: "4.9"
    name: performance-addon-operator
    source: performance-addon-operator
    sourceNamespace: openshift-marketplace
----
